### ISSUE TITLE
Integrations Test Failing After Upgrade To Docker Desktop v4.11.0

### ISSUE THREAD

**Issue by Jerrill** [camunda-community-hub/zeebe-client-csharp-bootstrap#49]
**Describe the bug**

After upgrading to Docker Desktop v4.11.0 the integrations test all failed. 

**To Reproduce**

1. Upgrade to v4.11.0
2. Try any integration test

**Expected behavior**

All integrations test pass individually after allowing Docker to tear down the test instances.

**Enviroment (please complete the following information):**

 - OS: Windows 11
 - Docker Desktop: v.4.11.0

**Additional context**

I was able to resolve the problem locally by upgrading the Testcontainers nuget package reference in the Tests project.

Previous: PackageReference Include="DotNet.Testcontainers" Version="1.6.0" 
New:   PackageReference Include="Testcontainers" Version="2.1.0"

**Comment by arjangeertsema** [comment]
@Jerrill thank you for reporting this bug. I have replaced the dependency and released it in the 0.1.5. version.
