### ISSUE TITLE
Feature to subscribe user task but not auto complete it 

### ISSUE THREAD

**Issue by waseemahmad31** [camunda-community-hub/zeebe-client-csharp-bootstrap#69]
**Is your feature request related to a problem? Please describe.**

We want to subscribe user task information and store its information, so that we can complete it later. However, current implementation auto completes user task after executing the handler.  
 
**Describe the solution you'd like**
User Task handler should be executed once but not auto completes it.

**Comment by arjangeertsema** [comment]
This library is not intended for user task handling. Therefore auto completing of service tasks is a logical feature. For user task related use cases you should use the tasklist api or create an exporter to process zeebe events.
