### ISSUE TITLE
Connect to Camunda Saas Instances & SM instances with TLS 

### ISSUE THREAD

**Issue by jothikiruthika** [camunda-community-hub/zeebe-client-csharp-bootstrap#75]
**Is your feature request related to a problem? Please describe.**

Unable to connect to a Camunda Saas Instance & SM Instance without plaintext

**Describe the solution you'd like**

Changes to the Zeebe client to connect to a Saas Instance & to connect to a SM instance with TLS security

**Additional context**

At the moment, we can only connect to a local instance of Camunda with plaintext security. The ZeebeClientAcceleratorOptions.ClientOptions only has GatewayAddress property. This could be extended to take values for Saas instances and enable connectivity with Saas Instances.

At the moment, any other address results in a Grpc.Core.RpcException
![image](https://user-images.githubusercontent.com/112610448/223897393-834a7176-49bc-47b2-b413-dddfc6956c2f.png)

**Comment by arjangeertsema** [comment]
@jothikiruthika this the wrong project, you should address the issue here: https://github.com/camunda-community-hub/zeebe-client-csharp-accelerator

**Comment by jothikiruthika** [comment]
Hi @arjangeertsema , I am unable to raise an issue with the https://github.com/camunda-community-hub/zeebe-client-csharp-accelerator. Looks like the issues tab is not available. Could you kindly help with this?

**Comment by arjangeertsema** [comment]
No, sorry I am not involved with that project. You could try to send a message to devrel@camunda.com
